# FROM almalinux:9
# RUN dnf install nginx -y
# CMD ["nginx","-g ","daemon off";]

# FROM almalinux:9

# LABEL author=”siva kumar reddy”\
#        Company=”joindevops”\
#        topic="dockerfiles"\
     

# RUN dnf install nginx -y

# CMD ["nginx", "-g", "daemon off;"]
FROM almalinux:9

LABEL author="siva kumar reddy" \
      company="joindevops" \
      topic="dockerfiles"

RUN dnf install nginx -y

CMD ["nginx", "-g", "daemon off;"]